### ISSUE TITLE
Sensor to detect when any track is armed?

### ISSUE THREAD

**Issue by josh-haas** [kubawolanin/ha-reaper#4]
Since the web interface can control track arming, is it possible to report armed tracks as a sensor in HA? Or, even as simple as if _any_ track is currently armed.

**Comment by kubawolanin** [comment]
Hey @josh-haas appreciate you checking out my integration 👋🏻 

It is possible to get armed tracks info - in underlying python-reaperdaw library I exposed needed data:
https://github.com/kubawolanin/python-reaperdaw#getstatus-response

How would you like to see this represented in HA sensor? As sensor's attributes (e.g. `number_of_tracks`)?

Cheers

**Comment by josh-haas** [comment]
For my purposes, even a binary `is_anything_armed` would suffice. I'm just looking to trigger something based on _anything_ at all being armed. Something more functional like `number_of_tracks` might have greater value to other users though? I'm sure there's plenty of other use cases for armed interaction. `number_of_tracks > 0` should serve my binary use case just as well.

**Comment by kubawolanin** [comment]
Gotcha, will see what I can do 👍🏻

**Comment by kubawolanin** [comment]
https://github.com/kubawolanin/python-reaperdaw/commit/ac65b4b064b2457f7de2dcc34069a4a2ebfa0f76

**Comment by kubawolanin** [comment]
![image](https://user-images.githubusercontent.com/2270505/141499488-292ee624-9aea-48d5-a79a-05c54eabbd55.png)

**Comment by kubawolanin** [comment]
Released in 0.2.2 @josh-haas 
Hope you enjoy it!

If you like my work please consider [supporting me](https://www.buymeacoffee.com/kubawolanin) or ⭐ the repository. Thanks!
